name: DeployGitHubPages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  update:
    runs-on: ubuntu-18.04
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: xyfuture/hugo_blog_env
          event-type: blog_update
